import express from "express";
import authMiddleware from "../../middleware/authMiddleware.js";
import roleMiddleware from "../../middleware/roleMiddleware.js";
import { ROLES } from "../../constants/roles.js";
import * as controller from "./admin.controller.js";

const router = express.Router();
router.use(authMiddleware, roleMiddleware(ROLES.ADMIN));

router.get("/dashboard", controller.fetchAdminDashboard);
router.get("/users", controller.fetchAdminUsers);
router.get("/users/:userId", controller.fetchAdminUserDetails);
router.patch("/users/:userId/:action", controller.updateAdminUser);
router.get("/vendors", controller.fetchAdminVendors);
router.get("/vendors/:vendorId", controller.fetchAdminVendorDetails);
router.patch("/vendors/:vendorId/:action", controller.updateAdminVendor);
router.get("/bookings", controller.fetchAdminBookings);
router.get("/bookings/:bookingId", controller.fetchAdminBookingDetails);
router.patch("/bookings/:bookingId/:action", controller.updateAdminBooking);
router.get("/payments", controller.fetchAdminPayments);
router.get("/payments/:paymentId", controller.fetchAdminPaymentDetails);
router.patch("/payments/:paymentId/:action", controller.updateAdminPayment);
router.get("/kyc-reviews", controller.fetchAdminKyc);
router.get("/kyc-reviews/:kycId", controller.fetchAdminKycDetails);
router.patch("/kyc-reviews/:kycId/:action", controller.reviewAdminKyc);
router.get("/change-requests", controller.fetchChangeRequests);
router.get("/change-requests/:requestId", controller.fetchChangeRequestDetails);
router.patch("/change-requests/:requestId/:action", controller.reviewAdminChangeRequest);
router.get("/deletion-requests", controller.fetchDeleteRequests);
router.get("/deletion-requests/:requestId", controller.fetchDeleteRequestDetails);
router.patch("/deletion-requests/:requestId/:action", controller.reviewAdminDeleteRequest);
router.get("/disputes", controller.fetchDisputes);
router.get("/disputes/:disputeId", controller.fetchDisputeDetails);
router.patch("/disputes/:disputeId/:action", controller.updateDispute);
router.get("/subscriptions", controller.fetchSubscriptions);
router.get("/spotlight", controller.fetchSpotlights);
router.patch("/spotlight/:spotlightId/resolve", controller.resolveSpotlight);
router.get("/policies", controller.fetchPolicies);
router.get("/policies/:policyId", controller.fetchPolicyDetails);
router.patch("/policies/:policyId/:action", controller.updatePolicyPublication);
router.get("/notifications", controller.fetchNotifications);
router.patch("/notifications/mark-all-read", controller.markAllAdminNotifications);
router.patch("/notifications/:notificationId/read", controller.markAdminNotification);
router.get("/audit-logs", controller.fetchAuditLogs);
router.get("/audit-logs/export", controller.exportAuditLogs);
router.post("/audit-logs/export", controller.exportAuditLogs);
router.post("/audit-logs/validate-integrity", controller.validateAuditIntegrity);
router.get("/reports", controller.fetchReports);
router.get("/reports/export", controller.exportReports);
router.post("/reports/export", controller.exportReports);
router.get("/settings", controller.fetchSettings);
router.patch("/settings/fees", controller.saveSettings);
router.patch("/settings/apply", controller.saveSettings);
router.get("/staff", controller.fetchStaff);
router.post("/staff/invite", controller.inviteStaff);
router.get("/support-requests", controller.fetchSupportRequests);

export default router;
